n = input('Digite algo: ')
print(f'Ele é númerico: {n.isnumeric()}')
print(f'Ele está em minusculo: {n.islower()}')
print(f'Ele está em maiusculo: {n.isupper()}')
print(f'Ele é decimal: {n.isdecimal()}')
print(f'Ele é letra: {n.isalpha()}')
print(f'Ele é string: {n.istitle()}')